version: "3.9"

networks:
  signup:
    driver: bridge

services:
  nginx:
    depends_on:
      - frontend
      - backend
    image: nginx:alpine
    container_name: signup-nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - signup

  frontend:
    image: hp4129889/signup:frontend
    container_name: signup-frontend
    restart: always
    networks:
      - signup

  backend:
    depends_on:
      - postgres
    image: hp4129889/signup:backend
    container_name: signup-backend
    command: sh -c "yarn migrate:r && yarn start"
    restart: always
    environment:
      - APP_SERVER_HOST=${APP_SERVER_HOST}
      - APP_PORT=${APP_PORT}
      - APP_DEBUG=${APP_DEBUG}
      - APP_ENVIRONMENT=${APP_ENVIRONMENT}
      - APP_API_PREFIX=${APP_API_PREFIX}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - MAILER_VERIFY_ROUTE=${MAILER_VERIFY_ROUTE}
      - MAILER_USER=${MAILER_USER}
      - MAILER_CLIENTID=${MAILER_CLIENTID}
      - MAILER_CLIENTSECRET=${MAILER_CLIENTSECRET}
      - MAILER_REFRESH_TOKEN=${MAILER_REFRESH_TOKEN}
      - MAILER_REDIRECT_URI=${MAILER_REDIRECT_URI}
    networks:
      - signup

  postgres:
    image: postgres
    container_name: signup-postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - signup

  pgadmin:
    image: dpage/pgadmin4
    container_name: signup-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - signup
